language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run lint
  - REACT_APP_BASENAME=/League-Quiz-Bank npm run build # to fix react-router giving blank page
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  local-dir: build
  on:
    branch: master
