// QUIZ ACTIONS
export const SET_QUIZLIST = 'SET_QUIZLIST';
export const DISPLAY_QUIZ = 'DISPLAY_QUIZ';

export const SET_TITLE = 'SET_TITLE';
export const SET_DESCRIPTION = 'SET_DESCRIPTION';
export const SET_LEVEL = 'SET_LEVEL';
export const SET_QUIZ_CLASS = 'SET_QUIZ_CLASS';

export const ADD_QUESTION = 'ADD_QUESTION';
export const UPDATE_QUESTION = 'UPDATE_QUESTION';
export const REMOVE_QUESTION = 'REMOVE_QUESTION';

export const SAVE_QUIZ = 'SAVE_QUIZ';

// QUESTION ACTIONS
export const UPDATE_PROMPT = 'UPDATE_PROMPT';
export const UPDATE_OPTION_TEXT = 'UPDATE_OPTION_TEXT';
export const ADD_OPTION = 'ADD_OPTION';
export const REMOVE_OPTION = 'REMOVE_OPTION';
export const TOGGLE_OPTION_AS_ANSWER = 'TOGGLE_OPTION_AS_ANSWER';
