//QUESTION TYPES
export const SINGLE_SELECT_QUESTION = 'SINGLE_SELECT_QUESTION';
export const MULTI_SELECT_QUESTION = 'MULTI_SELECT_QUESTION';
export const FREE_TEXT_QUESTION = 'FREE_TEXT_QUESTION';

//OPTIONS
export const TRUE = 'TRUE';
export const FALSE = 'FALSE';
